// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/9/2026, 1:51:10 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/nadoe/WebstormProjects/mitso-record-app/frontend/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nadoe/WebstormProjects/mitso-record-app/frontend/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nadoe/WebstormProjects/mitso-record-app/frontend/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nadoe/WebstormProjects/mitso-record-app/frontend/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nadoe/WebstormProjects/mitso-record-app/frontend/src/plugins/**/*.{js,ts,mjs}","/Users/nadoe/WebstormProjects/mitso-record-app/frontend/src/composables/**/**/*.{js,ts,mjs}","/Users/nadoe/WebstormProjects/mitso-record-app/frontend/src/utils/**/**/*.{js,ts,mjs}","/Users/nadoe/WebstormProjects/mitso-record-app/frontend/src/composables/**/*.{js,ts,mjs}","/Users/nadoe/WebstormProjects/mitso-record-app/frontend/src/utils/**/*.{js,ts,mjs}","/Users/nadoe/WebstormProjects/mitso-record-app/frontend/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nadoe/WebstormProjects/mitso-record-app/frontend/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/nadoe/WebstormProjects/mitso-record-app/frontend/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/nadoe/WebstormProjects/mitso-record-app/frontend/src/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;